[package]
name = "we-snark"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-serialize = "0.5.0"
rand = "0.9.2"
sha2 = "0.10.9"
